# Prometheus Alerts ConfigMap for Terraform Visualization Tool
# prometheus-community/prometheus v15.x
# prometheus-community/alertmanager v0.25.x

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: monitoring
  labels:
    app: terraform-visualizer
    component: monitoring
data:
  prometheus-alerts.yml: |
    groups:
      # Visualization Performance Monitoring
      - name: VisualizationPerformance
        rules:
        - alert: HighVisualizationLatency
          expr: visualization_update_seconds > 1
          for: 5m
          labels:
            severity: warning
            component: frontend
          annotations:
            summary: High visualization update latency
            description: Graph visualization updates taking longer than 1 second, exceeding performance benchmark

      # Parser Performance Monitoring
      - name: ParserPerformance
        rules:
        - alert: SlowParsingTime
          expr: parse_duration_seconds > 3
          for: 5m
          labels:
            severity: warning
            component: parser
          annotations:
            summary: Slow Terraform parsing time
            description: Parser taking longer than 3 seconds to process files, exceeding performance benchmark

      # API Performance Monitoring
      - name: APIPerformance
        rules:
        - alert: HighAPILatency
          expr: http_request_duration_seconds > 0.2
          for: 5m
          labels:
            severity: warning
            component: backend
          annotations:
            summary: High API response time
            description: API endpoints responding slower than 200ms, exceeding performance benchmark

      # System Resource Monitoring
      - name: SystemResources
        rules:
        - alert: HighCPUUsage
          expr: container_cpu_usage_seconds_total{container=~"frontend|backend|parser"} > 0.8
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: High CPU utilization
            description: Container CPU usage above 80% for 10 minutes, indicating potential resource constraints
        - alert: HighMemoryUsage
          expr: container_memory_usage_bytes{container=~"frontend|backend|parser"} / container_memory_limit_bytes > 0.9
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: High memory utilization
            description: Container memory usage above 90% for 10 minutes, approaching resource limits

      # Error Rate Monitoring
      - name: ErrorRates
        rules:
        - alert: HighErrorRate
          expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.01
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: High error rate detected
            description: Error rate above 1% for 5 minutes, indicating potential system issues

  alertmanager.yml: |
    route:
      receiver: 'slack'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - match:
            severity: critical
          receiver: pagerduty
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
        - match:
            severity: warning
          receiver: slack
          group_wait: 1m
          group_interval: 10m
          repeat_interval: 12h

    receivers:
      - name: 'pagerduty'
        pagerduty_configs:
          - service_key: ${PAGERDUTY_KEY}
            description: '{{ .CommonAnnotations.description }}'
            severity: '{{ .CommonLabels.severity }}'

      - name: 'slack'
        slack_configs:
          - channel: '#terraform-alerts'
            title: '{{ .CommonAnnotations.summary }}'
            text: '{{ .CommonAnnotations.description }}'
            send_resolved: true