# Kubernetes ConfigMaps for Terraform Visualization Tool
# Version: 1.25+
# Purpose: Non-sensitive configuration management for frontend, backend, and parser services

---
# Backend Service Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: terraform-visualizer
  labels:
    app: terraform-visualizer
    component: backend
data:
  # Server Configuration
  NODE_ENV: "production"
  PORT: "3000"
  API_VERSION: "v1"
  
  # CORS Settings
  CORS_ORIGIN: "https://terraform-visualizer.example.com"
  
  # Database Configuration
  MONGODB_HOST: "mongodb.terraform-visualizer.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "terraform_visualizer"
  
  # Cache Configuration
  REDIS_HOST: "redis.terraform-visualizer.svc.cluster.local"
  REDIS_PORT: "6379"
  
  # External Services
  GITHUB_API_URL: "https://api.github.com"
  
  # Application Settings
  LOG_LEVEL: "info"
  RATE_LIMIT_WINDOW: "15m"
  RATE_LIMIT_MAX_REQUESTS: "100"

---
# Frontend Application Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: terraform-visualizer
  labels:
    app: terraform-visualizer
    component: frontend
data:
  # Environment Configuration
  NODE_ENV: "production"
  
  # API Configuration
  REACT_APP_API_URL: "https://api.terraform-visualizer.example.com"
  REACT_APP_WS_URL: "wss://api.terraform-visualizer.example.com"
  
  # Authentication
  REACT_APP_GITHUB_AUTH_URL: "https://github.com/login/oauth/authorize"
  
  # Application Settings
  REACT_APP_VERSION: "1.0.0"
  REACT_APP_LOG_LEVEL: "error"
  
  # Visualization Settings
  REACT_APP_GRAPH_LAYOUT: "hierarchical"
  REACT_APP_MAX_ZOOM: "3"
  REACT_APP_MIN_ZOOM: "0.1"

---
# Parser Service Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: parser-config
  namespace: terraform-visualizer
  labels:
    app: terraform-visualizer
    component: parser
data:
  # Server Configuration
  NODE_ENV: "production"
  PORT: "3001"
  LOG_LEVEL: "info"
  
  # Parser Settings
  PARSER_TIMEOUT: "30000"
  MAX_FILE_SIZE: "1048576"
  CACHE_TTL: "3600"
  
  # Cache Configuration
  REDIS_HOST: "redis.terraform-visualizer.svc.cluster.local"
  REDIS_PORT: "6379"
  
  # Terraform Support
  SUPPORTED_TERRAFORM_VERSIONS: "1.2.0,1.3.0,1.4.0,1.5.0"