---
# Backend Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: terraform-visualizer
  labels:
    app: terraform-visualizer
    component: backend
    managed-by: terraform-visualizer-operator
  annotations:
    kubernetes.io/created-by: terraform-visualizer-operator
    encryption.kubernetes.io/kms-key: arn:aws:kms:region:account:key/backend-key
    secret.kubernetes.io/rotation-period: 30d
type: Opaque
data:
  JWT_SECRET: <base64_encoded>
  GITHUB_CLIENT_SECRET: <base64_encoded>
  MONGODB_PASSWORD: <base64_encoded>
  REDIS_PASSWORD: <base64_encoded>
  ENCRYPTION_KEY: <base64_encoded>
  API_ENCRYPTION_KEY: <base64_encoded>
  DATADOG_API_KEY: <base64_encoded>
---
# Frontend Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: terraform-visualizer
  labels:
    app: terraform-visualizer
    component: frontend
    managed-by: terraform-visualizer-operator
  annotations:
    kubernetes.io/created-by: terraform-visualizer-operator
    encryption.kubernetes.io/kms-key: arn:aws:kms:region:account:key/frontend-key
    secret.kubernetes.io/rotation-period: 30d
type: Opaque
data:
  GITHUB_CLIENT_ID: <base64_encoded>
  AUTH0_CLIENT_SECRET: <base64_encoded>
  API_KEY: <base64_encoded>
  MONITORING_TOKEN: <base64_encoded>
---
# Parser Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: parser-secrets
  namespace: terraform-visualizer
  labels:
    app: terraform-visualizer
    component: parser
    managed-by: terraform-visualizer-operator
  annotations:
    kubernetes.io/created-by: terraform-visualizer-operator
    encryption.kubernetes.io/kms-key: arn:aws:kms:region:account:key/parser-key
    secret.kubernetes.io/rotation-period: 30d
type: Opaque
data:
  ENCRYPTION_KEY: <base64_encoded>
  API_KEY: <base64_encoded>
  GITHUB_ACCESS_TOKEN: <base64_encoded>
  TERRAFORM_REGISTRY_TOKEN: <base64_encoded>
---
# RBAC Role for Backend Service
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-secrets-reader
  namespace: terraform-visualizer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["backend-secrets"]
  verbs: ["get"]
---
# RBAC Role for Frontend Service
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-secrets-reader
  namespace: terraform-visualizer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["frontend-secrets"]
  verbs: ["get"]
---
# RBAC Role for Parser Service
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: parser-secrets-reader
  namespace: terraform-visualizer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["parser-secrets"]
  verbs: ["get"]
---
# RBAC RoleBinding for Backend Service
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-secrets-reader-binding
  namespace: terraform-visualizer
subjects:
- kind: ServiceAccount
  name: backend
  namespace: terraform-visualizer
roleRef:
  kind: Role
  name: backend-secrets-reader
  apiGroup: rbac.authorization.k8s.io
---
# RBAC RoleBinding for Frontend Service
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-secrets-reader-binding
  namespace: terraform-visualizer
subjects:
- kind: ServiceAccount
  name: frontend
  namespace: terraform-visualizer
roleRef:
  kind: Role
  name: frontend-secrets-reader
  apiGroup: rbac.authorization.k8s.io
---
# RBAC RoleBinding for Parser Service
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: parser-secrets-reader-binding
  namespace: terraform-visualizer
subjects:
- kind: ServiceAccount
  name: parser
  namespace: terraform-visualizer
roleRef:
  kind: Role
  name: parser-secrets-reader
  apiGroup: rbac.authorization.k8s.io